language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: LARAVEL='8.*' TESTBENCH='6.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4
      env: LARAVEL='8.*' TESTBENCH='6.*' COMPOSER_FLAGS='--prefer-stable'
    - php: 8.0
      env: LARAVEL='8.*' TESTBENCH='6.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 8.0
      env: LARAVEL='8.*' TESTBENCH='6.*' COMPOSER_FLAGS='--prefer-stable'
  fast_finish: true

before_install:
  - sudo apt-get update
  - travis_retry composer self-update
  - composer config discard-changes true
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --no-suggest
  - sudo add-apt-repository -y ppa:mc3man/xerus-media
  - sudo apt-get -qq update
  - sudo apt-get install -y --allow-unauthenticated software-properties-common ffmpeg libmagickwand-dev imagemagick php-pear
  - echo '\n\n\n' | sudo pecl install imagick
  - echo 'extension=imagick.so' >> `php --ini | grep 'Loaded Configuration' | sed -e 's|.*:\s*||'`

script:
  - vendor/bin/phpunit
